#默认环境
server:
  port: 8900
spring:
  #redis
  redis:
    host: 127.0.0.1
    port: 6379
   #实现热部署
  devtools:
    restart:
      enabled: true
      #设置重启的目录,paths添加哪个目录的文件需要restart，exclude不需要
      additional-paths: src/main/java
      additional-exclude: WEB-INF/**
  profiles:
    active: dev
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: lms
    password: oracle
    url: jdbc:oracle:thin:@192.168.2.26:1521:jiexinv68
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

###mybatis配置
mybatis:
  type-aliases-package: com.seecen.entity
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
     #开启MyBatis的二级缓存，一级缓存默认开启
    cache-enabled: true
  mapper-locations: classpath:mappers/*.xml

pagehelper:
  reasonable: true
  support-methods-arguments: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
#日志打印
logging:
  level:
    com.seecen: debug

